server:
  port:
    8888

spring:
  application:
    name: gateway

  cloud:
    discovery:
      enabled: true

### c'est la configuration statique des routes (elle est remplacée par la configuration statique java au niveau de main)
#    gateway:
#      routes:
#        - id: r1
#          uri: http://localhost:8081
#          predicates:
#            - Path=/customers/**
#        - id: r2
#          uri: http://localhost:8082
#          predicates:
#            - Path=/products/**